# Generated by Django 4.1.1 on 2022-10-05 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='charge',
            fields=[
                ('idcharge', models.AutoField(primary_key=True, serialize=False)),
                ('rinciancharge', models.CharField(max_length=10)),
                ('jenischarge', models.CharField(max_length=30)),
                ('hargacharge', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='owner',
            fields=[
                ('idowner', models.AutoField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=50)),
                ('jeniskelamin', models.CharField(max_length=10)),
                ('nohandphone', models.IntegerField()),
                ('alamat', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='pakaian',
            fields=[
                ('idpakaian', models.AutoField(primary_key=True, serialize=False)),
                ('jenispakaian', models.CharField(max_length=30)),
                ('ukuranpakaian', models.CharField(max_length=10)),
                ('hargapakaian', models.FloatField()),
                ('konfirmasipakaian', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='pelanggan',
            fields=[
                ('idpelanggan', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=50)),
                ('jeniskelamin', models.CharField(max_length=10)),
                ('nohandphone', models.IntegerField()),
                ('alamat', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='peminjaman',
            fields=[
                ('idpeminjaman', models.AutoField(primary_key=True, serialize=False)),
                ('tanggalsewa', models.DateField()),
                ('lamasewa', models.CharField(max_length=30)),
                ('tanggalkembali', models.DateField()),
                ('statuspeminjaman', models.BooleanField(null=True)),
                ('idowner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='butiklosik2.owner')),
                ('idpakaian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='butiklosik2.pakaian')),
                ('idpelanggan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='butiklosik2.pelanggan')),
            ],
        ),
        migrations.CreateModel(
            name='detailcharge',
            fields=[
                ('iddetailcharge', models.AutoField(primary_key=True, serialize=False)),
                ('jumlahitemcharge', models.IntegerField()),
                ('idcharge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='butiklosik2.charge')),
                ('idpeminjaman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='butiklosik2.peminjaman')),
            ],
        ),
    ]
